### ISSUE TITLE
How to fix "UnicodeEncodeError: 'cp949'"

### ISSUE THREAD

**Issue by rejeena** [newpro/aloha-chatbot#3]
After I run sample.py code, I got error message

"UnicodeEncodeError: 'cp949' codec can't encode character '\xa0' in position 800: illegal multibyte sequence"

I don't know how to fix it.
please help me..
I really want to run your codes, and get "sheldon cooper's messages" 

![image](https://user-images.githubusercontent.com/11676635/88586396-4ed98380-d08f-11ea-950e-405e6abab26b.png)

**Comment by newpro** [comment]
Interesting. Seems like your OS, possibly windows, does not recognize latin 1 space. I thought codec would take care of this already, apparently not.

Try change [this line](https://github.com/newpro/aloha-chatbot/blob/master/src/core.py#L263) to [explicitly pass in ecoding as UTF-8.](https://stackoverflow.com/questions/934160/write-to-utf-8-file-in-python)

```python
train_ptr = codecs.open(train_f, 'a+', encoding='utf-8')
```

Also changes all three variables: train_ptr, valid_ptr, test_ptr as well.


If still gives u error, base on this [thread](https://stackoverflow.com/questions/10993612), try add this line under [line 275](https://github.com/newpro/aloha-chatbot/blob/master/src/core.py#L275)

```python
line = unicodedata.normalize("NFKD", line)
```
