### ISSUE TITLE
 could you offer original script dialogue data？

### ISSUE THREAD

**Issue by valar000** [newpro/aloha-chatbot#5]
I want to know character for dialogue and multi-turn dialogue.

**Comment by newpro** [comment]
We can not do this.

At the time of research (presumably still now), the character features from tvtropes.org are allowed to be used in our public releases, but the scripts are copyrighted by movie/TV studios. We were advised at the time of publication that we do not have the right to release it.

We purposely chose well-known movies and TV shows in this research work; researchers should be able to recover the dialogues from various websites. Sorry for the inconvenience.
